### ISSUE TITLE
Second Degree Black Belt : XML External Entities environment hostname is not getting set

### ISSUE THREAD

**Issue by bilalk88** [OWASP/SecureCodingDojo#139]
While I'm trying to solve the Second Degree Black Belt : XML External Entities challenge, observed that levering the previous challenge i.e. Injection got that there is one  'connecttocommandproc.sh' file when I try to read to content it is observed that the in URL only host2:8080 is mentioned, I think when deploying the hackerden challenge the environment value for host2 and flag-_secret values are not getting set.
Can someone please look into this and help me to get the host2 value,

**Comment by bilalk88** [comment]
Also, just to check whether the XXE Flag value are getting set or not. from the codebase figured out, how to solve the solve challenge and did manage to solve partial part however after getting the 'JSESSIONID' used the commandproc and got the result as "_Good for you! You got this far. Here's your challenge code url:_" , however in the response not getting the challengeURL after solving it.
for reference, refer to below screenshot.
![image](https://github.com/OWASP/SecureCodingDojo/assets/10231632/108d3e95-9a24-4d9a-9f6a-7d65204b062d)
cc - @paul-ion

**Comment by paul-ion** [comment]
Hi @bilalk88 , the hosted version of the Dojo is a few versions behind due to some resource compute issues. Working on solving.

**Comment by paul-ion** [comment]
@bilalk88 this issue should now be solved

**Comment by avinashsolankim** [comment]
This Issue is still not exist. $FLAG_SECRET values is not getting set.
In Both challenges
1. Second Degree Black Belt : XML External Entities 
2. Second Degree Black Belt : Using Components with Known Vulnerabilities & Insecure Deserialization 
<img width="699" alt="2024-07-15 02_04_12-Mozilla Firefox" src="https://github.com/user-attachments/assets/f16d521c-c146-4ebe-b2a4-11c581cfbbd3">

**Comment by harish-103** [comment]
@bilalk88 @paul-ion @mfoo @Jleagle @philipbalinov 
After successfully obtaining the FLAG-xxe-, I’m unsure how to proceed further to complete the remaining steps of the challenge. I need guidance on exploiting the XXE vulnerability effectively to achieve the desired outcome.

Could you please provide detailed steps or insights to help me move forward and complete the challenge?

**Comment by paul-ion** [comment]
This issue is now closed. 

@harish-103 regarding solutions for the Second Degree challenges, they are currently unavailable intentionally. This is a higher difficulty module.  That being said, please read the challenge description carefully as there may be things that you have overlooked.

Also it is not good etiquette to tag random contributors in your posts. Please refrain from doing this. Especially since this is not a defect but an assistance request with the training.

**Comment by Sakters** [comment]
<img width="781" alt="Screenshot 2024-12-15 at 1 55 59 AM" src="https://github.com/user-attachments/assets/67a933b7-e27e-4e76-ae9a-4d3a5c92defb" />


@paul-ion Sorry to bother you, I have followed the steps multiple times and tried all the ways possible to STOP the command. 
However after sending the BaseCommand , Im getting a 200 response in return but the page is blank
<img width="524" alt="Screenshot 2024-12-15 at 1 57 28 AM" src="https://github.com/user-attachments/assets/9ec66944-c160-4cf9-b5e9-c78ba7205e5b" />

**Comment by Sakters** [comment]
@paul-ion I have tried 100 ways to crack it, Please let me know If Im missing anything.

**Comment by paul-ion** [comment]
Please do not use the issues section as a forum for help with the training challenges. The issues section is only intended for reporting defects.

**Comment by Tomasz-Silpion** [comment]
> Hi [@bilalk88](https://github.com/bilalk88) , the hosted version of the Dojo is a few versions behind due to some resource compute issues. Working on solving.

> [@bilalk88](https://github.com/bilalk88) this issue should now be solved

Sorry, I've got into the same issue, and as I ran into it after hours of trying to solve it, I would like a clarification.

`Good for you! You got this far. Here's your challenge code url: FLAG-xxe-`

Is this message part of the challenge, or some sort of a securecodingdojo/hackerden-host2 Docker image bug?

**Comment by 13ph03nix** [comment]
I ran into the same issue. The root cause was that the `FLAG_SECRET` environment variable was not defined in the: https://github.com/OWASP/SecureCodingDojo/blob/94ad6afe80c870281a6e48788cbfb55f94a9100a/hackerden/docker-compose.yml#L44-L45

In JavaScript, this means `const FLAG2 = "FLAG-xxe-" + process.env.FLAG_SECRET` becomes `"FLAG-xxe-undefined"`. As a result, the flag detection logic looks for `FLAG-xxe-undefined` while the actual output only contains `FLAG-xxe-`, leading to no match and preventing the flag from being replaced with the challenge code URL.

<img width="862" height="110" alt="Image" src="https://github.com/user-attachments/assets/8c9452ee-f626-4839-ac57-ae3ed9e9a17a" />

https://github.com/OWASP/SecureCodingDojo/blob/94ad6afe80c870281a6e48788cbfb55f94a9100a/hackerden/front/network-utils.js#L9-L11
